// photos
export const FETCH_PHOTOS_REQUEST = "FETCH_PHOTOS_REQUEST";
export const FETCH_PHOTOS_SUCCESS = "FETCH_PHOTOS_SUCCESS";
export const FETCH_PHOTOS_FAILURE = "FETCH_PHOTOS_FAILURE";
export const LIKE_PHOTO = "LIKE_PHOTO";
export const UNLIKE_PHOTO = "UNLIKE_PHOTO";

// photo
export const ADD_PHOTO_REQUEST = "ADD_PHOTO_REQUEST";
export const ADD_PHOTO_SUCCESS = "ADD_PHOTO_SUCCESS";
export const ADD_PHOTO_FAILURE = "ADD_PHOTO_FAILURE";
export const SET_PHOTO_URI = "SET_PHOTO_URI";
export const SET_PHOTO_SOURCE = "SET_PHOTO_SOURCE";
export const SET_PHOTO_CAPTION = "SET_PHOTO_CAPTION";
export const SET_PHOTO_LOCATION = "SET_PHOTO_LOCATION";

// comment
export const ADD_COMMENT_REQUEST = "ADD_COMMENT_REQUEST";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FAILURE = "ADD_COMMENT_FAILURE";
export const SET_COMMENT_TEXT = "SET_COMMENT_TEXT";
export const SET_PHOTO_COMMENTS = "SET_PHOTO_COMMENTS";

// auth
export const CHECK_LOGIN_REQUEST = "CHECK_LOGIN_REQUEST";
export const CHECK_LOGIN_SUCCESS = "CHECK_LOGIN_SUCCESS";
export const CHECK_LOGIN_FAILURE = "CHECK_LOGIN_FAILURE";
export const LOGIN_GOOGLE_REQUEST = "LOGIN_GOOGLE_REQUEST";
export const LOGIN_GOOGLE_SUCCESS = "LOGIN_GOOGLE_SUCCESS";
export const LOGIN_GOOGLE_FAILURE = "LOGIN_GOOGLE_FAILURE";
export const LOGIN_FACEBOOK_REQUEST = "LOGIN_FACEBOOK_REQUEST";
export const LOGIN_FACEBOOK_SUCCESS = "LOGIN_FACEBOOK_SUCCESS";
export const LOGIN_FACEBOOK_FAILURE = "LOGIN_FACEBOOK_FAILURE";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";
